### PR TITLE
Frontend/sounds

### PR DESCRIPTION
**Pull request by Qqwy**
Adds sounds to:

- Login
- Switching menu tab
- Logout.

Also improves the login form by adding a waiting state while we attempt to log the user in, and another error message.

To load audio files, it was necessary to 'eject' the react project from `create-react-app`, which means that there are now some new configuration files. The only part that was touched, were the webpack configuration files in `config/`, following what is described here:  http://www.mikedoesweb.com/2017/adding-mp3-files-to-a-create-react-app-app/

### CODE REVIEW

**Comment by Qqwy** [comment]
Fixes #85

**Comment by dunnkers** [comment]
Is there really no way to implement this without having to eject the config files? All 'ejected' code clutters the codebase with code that is otherwise abstracted away. I think the [process of upgrading](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#updating-to-new-releases) a create-react-app is a little harsher as well. If not possible without ejecting I think we'll stick with your option.

**Comment by Qqwy** [comment]
It is a really weird design choice that you cannot opt-in into some of the configuration files that `create-react-app` uses under the hood. It is an all-or-nothing kind of deal.

There is one alternative I can see, which is to fork `create-react-app` and alter the config files there.


**I think the smartest short-term solution would be to create a `presentation` branch which merges `development` with `frontend/sound` (rather than merging this branch into `development` in its current state).** 
This would mean we can perform the procedure described above after the presentation without any hassle. un-doing the eject after having merged this PR into development probably is a lot harder.

**Comment by dunnkers** [comment]
Yes I agree with creating a separate presentation branch to show off the demo with! We’ll discuss about the actual sound implementation later on.

**Comment by Qqwy** [comment]
I'll see if I have time this evening/tomorrow early morning to extract the sound stuff to its own branch ;-).

**Comment by Qqwy** [comment]
Closed in favour of #134

**Pull request closed without merging**
