### PR TITLE
Fixing periodic fetching, refactoring backend code

### PR DESCRIPTION
**Pull request by Qqwy**
Changes:

1. Background tasks now properly are able to perform fetching logic. What solves is is the call to `database_connection().sync()` at the start of each background-task; turns out that the task pool re-uses processes (there's one process per CPU core), whose database connections grow stale when executing a new task for the same dashboard as before.
2. Moving of modules:
  - `dashboard_fetching` now lives in `dashboard.services.fetching`
  - `impl.fetch` now lives in its own package named `flask_monitoring_dashboard_client`.
  - `periodic_tasks` now lives in its own package
  -  `dashboard_repository` and `user_repository` are renamed to just `repository` in their respective folders.
3. Moving seeding logic
  - The seeding logic is moved from the respective `repository` to `services.seeding`, because this is definitely a separate concern, since we were starting to introduce circular dependencies.
4. Renaming methods
  - The contents of `dashboard_fetching` (now `dashboard.services.fetching`) have been overhauled to have more descripitive names.
5. Fixing return types of methods in `dashboard_fetching (now `dashboard.services.fetching`)
  - There were a couple of methods that returned `None` and then in the method they were called from, this special case was explicitly checked for (doing an early return) before iterating over the normal list result, instead of just returning `[]` and doing a (no-op) iteration over an empty list.
6. Refactoring imports: So that instead of `from app.foo import bar as foo_bar, baz as foo_baz, qux as foo_qux` we now have `import app.foo as foo` (and then use `foo.bar, foo.baz, foo.qux` as calls)

I think that's all ^^.

### CODE REVIEW

**Comment by Qqwy** [comment]
Oh, and there is some new/improved  documentation. :D

**Comment by Qqwy** [comment]
backend_package_dag

^This is how the different backend packages depend on one-another. The `impl` directory now could be completely removed.

Extra changes were:
- The `impl.logger` now lives in `pydash_logger`.
- The `impl.database` now lives in `pydash_database`.

It might be necessary to clear your database files and re-start your database because some core objects were moved (mostly the MultipleIndexedPersistenCollection) so there might be problems with unpickling the 'old' instance of them.

**Comment by Qqwy** [comment]
Because of all the refactoring, I was able to remove the `sync()` call and instead use a `transaction.begin()` at the end of the update functions in the repositories. That's nicer because now the Repository abstraction is not leaky anymore.

**Comment by Qqwy** [comment]
Oh, and it now also contains basic code to set up testing. After running `pipenv install --dev`, just run `pytest` and it will:

- run tests in parallel depending on how many CPU cores you have
- print code coverage once the tests are done.

**Comment by TheVeggydude** [comment]
I've ran it as well and had not issues now, so merging the pull request

**Pull request merged**
